#include "Game/ControllerBehavior/Wave/wave_progress.h"
#include <cassert>
#include <iostream>
#include <limits>
int main() {
    WaveSettings settings;
    settings.clearResultTransitionDelay = 3.0f;
    settings.gameOverResultTransitionDelay = 4.0f;
    assert(GetResultTransitionDelay(WaveProgress::State::Complete, settings) == 3.0f);
    assert(GetResultTransitionDelay(WaveProgress::State::GameOver, settings) == 4.0f);
    settings.clearResultTransitionDelay = -1.0f;
    assert(GetResultTransitionDelay(WaveProgress::State::Complete, settings) == 0.0f);
    settings.waveCount = 2;
    settings.firstTargetPoints = 20;
    settings.targetPointsIncrement = 10;
    settings.preparationDuration = 1;
    settings.intermissionDuration = 1;
    settings.cleanupDelay = 2;
    WaveProgress progress;
    progress.Update(10, false, 0, settings);
    assert(progress.state == WaveProgress::State::WaitingForWorld);
    progress.Update(0, true, 0, settings);
    assert(progress.state == WaveProgress::State::Preparing);
    progress.Update(1, true, 0, settings);
    assert(progress.waveNumber == 1 && progress.targetPoints == 20);
    progress.AddDefeatPoints(20, settings);
    assert(progress.state == WaveProgress::State::ClearImpact);
    assert(GetWaveClearImpactDuration(settings) == 0.6f);
    progress.FinishClearImpact(settings);
    assert(progress.state == WaveProgress::State::Intermission);
    progress.Update(1, true, 1, settings);
    progress.AddDefeatPoints(10, settings);
    assert(progress.totalScore == 30 && progress.wavePoints == 30 && progress.GetCleanupRemaining() == 1);
    progress.Update(.5f, true, 0, settings);
    assert(progress.waveNumber == 1 && !progress.ShouldCleanupEnemies());
    progress.Update(.5f, true, 1, settings);
    assert(progress.ShouldCleanupEnemies());
    progress.MarkCleanupIssued();
    progress.AddDefeatPoints(100, settings);
    assert(progress.totalScore == 30);
    progress.Update(10, true, 1, settings);
    assert(progress.waveNumber == 1);
    progress.Update(0, true, 0, settings);
    assert(progress.state == WaveProgress::State::Battle && progress.waveNumber == 2);
    assert(progress.wavePoints == 0 && progress.targetPoints == 30);
    progress.AddDefeatPoints(30, settings);
    assert(progress.state == WaveProgress::State::ClearImpact);
    progress.FinishClearImpact(settings);
    progress.Update(1, true, 1, settings);
    progress.AddDefeatPoints(10, settings);
    assert(progress.totalScore == 70);
    progress.Update(1, true, 0, settings);
    assert(progress.state == WaveProgress::State::Intermission && progress.ShouldCleanupEnemies());
    progress.MarkCleanupIssued();
    progress.Update(0, true, 0, settings);
    assert(progress.state == WaveProgress::State::Complete);
    progress.AddDefeatPoints(100, settings);
    assert(progress.totalScore == 70);
    progress.state = WaveProgress::State::GameOver;
    progress.Update(10, true, 0, settings);
    progress.AddDefeatPoints(100, settings);
    assert(progress.state == WaveProgress::State::GameOver && progress.totalScore == 70);
    progress.Update(std::numeric_limits<float>::quiet_NaN(), true, 0, settings);
    assert(progress.state == WaveProgress::State::GameOver);
    WaveProgress other;
    settings.preparationDuration = 0;
    settings.cleanupDelay = 0;
    settings.intermissionDuration = 5;
    other.Update(0, true, 0, settings);
    other.AddDefeatPoints(20, settings);
    assert(other.state == WaveProgress::State::ClearImpact);
    other.FinishClearImpact(settings);
    assert(other.ShouldCleanupEnemies());
    other.MarkCleanupIssued();
    other.Update(4, true, 0, settings);
    assert(other.state == WaveProgress::State::Intermission);
    other.Update(1, true, 0, settings);
    assert(other.state == WaveProgress::State::Battle && other.waveNumber == 2);
    std::cout << "wave_progress_tests passed\n";
}
